### PR TITLE
Fix location of layers

### LINKED ISSUE #309: Bug: Incorrect location for @layer prelude
When parsing code like this:

```css
@layer foo { a { color: red } }
```

CSSTree incorrectly reports the location of the prelude as going from column 11 to column 12, which is the space after `foo` and before `{`.

Expected: prelude location going from column 8 to column 11.

Reproduction:
https://stackblitz.com/edit/stackblitz-starters-2uu7fw?file=index.js

### PR DESCRIPTION
**Pull request by nzakas**
This pull request includes changes to improve the accuracy of location calculations for CSS layers in the parser and adds a new test case to ensure this functionality is working correctly. The most important changes include adding a new test case in `parse.js` and modifying the `parse` function in `Layer.js` to correctly track token positions.

Attempts to fix #309.

Improvements to location calculations:

* [`lib/syntax/node/Layer.js`](diffhunk://#diff-9710abbd195ae61714a7d60958f7018ecab7b9fc8c073ab82480226122014e7cR11-R24): Modified the `parse` function to correctly track the start and end token positions when parsing layer names.

New test case:

* [`lib/__tests/parse.js`](diffhunk://#diff-c4e30655c2d8cb0f22ee50b0e16a062fa38a8631331b8acef0c67c2588b17f33R465-R499): Added a new test case to verify the correct calculation of layer locations in the AST. This test case ensures that the parser correctly identifies the start and end positions of various nodes within a stylesheet that includes layers.

**Problem:** At least to me, it looks like the starting position of `@layer` is off by one in the test. I left the test in a failing state to see if you can verify either that my test is incorrect or that the positioning still has a bug.

### CODE REVIEW

File: lib/__tests/parse.js [hunk 1]
```diff
@@ -462,5 +462,40 @@ describe('parse', () => {
                 [189, 4, 79, 'String']
             ]);
         });
+
+        it('should calculate location of layer correctly', () => {
```
Comment (lahmatiy) [inline lib/__tests/parse.js:466]: A separate test case for this isn't necessary. You can add a couple of `@layer` at-rules (one with a single name and another containing `.`) to `fixture/stringify.css` to cover overall parsing correctness, including locations. To update `fixture/stringify.ast`, temporarily uncomment this [line](https://github.com/csstree/csstree/blob/master/lib/__tests/common.js#L26), run `npm test`, and then comment it out again afterward.

File: lib/syntax/node/Layer.js [hunk 2]
```diff
@@ -8,16 +8,20 @@ export const structure = {
 };
 
 export function parse() {
+
+    let tokenStart = this.tokenStart;
+    let tokenEnd = this.tokenEnd;
```
Comment (lahmatiy) [inline lib/syntax/node/Layer.js:13]: No need for `tokenEnd`, it will be available as `this.tokenStart` (the end of consumed tokens will be a start of parser's current token) at the function return.

File: lib/__tests/parse.js (hunk 1 above)
Comment (nzakas) [reply lib/__tests/parse.js]: Got it. 👍

File: lib/syntax/node/Layer.js (hunk 2 above)
Comment (nzakas) [reply lib/syntax/node/Layer.js]: Ah good call.

File: lib/__tests/parse.js [hunk 3]
```diff
@@ -462,5 +462,6 @@ describe('parse', () => {
                 [189, 4, 79, 'String']
             ]);
         });
+
```
Comment (lahmatiy) [inline lib/__tests/parse.js:465]: Missed new newline (remove pls)

File: lib/syntax/node/Layer.js [hunk 4]
```diff
@@ -8,6 +8,8 @@ export const structure = {
 };
 
 export function parse() {
+
```
Comment (lahmatiy) [inline lib/syntax/node/Layer.js:11]: No empty line here please

File: fixtures/stringify.css [hunk 5]
```diff
@@ -9,6 +9,26 @@
...
+    }
+
+    @layer bar {
+        .class2 {
+            color: red;
+        }
+    }
+}
+
+@layer . {
```
Comment (lahmatiy) [inline fixtures/stringify.css:26]: When I wrote about a layer name with a dot, I meant something like `foo.bar`. A single dot is incorrect layer name. Also a layer name can be omitted, good to add such a case as well.
https://drafts.csswg.org/css-cascade-5/#layer-names
image

https://drafts.csswg.org/css-cascade-5/#unnamed-layers
image

**Review by lahmatiy — CHANGES_REQUESTED** [review]

File: fixtures/stringify.css (hunk 5 above)
Comment (nzakas) [reply fixtures/stringify.css]: Ah gotcha.

**Comment by lahmatiy** [comment]
All good. Thank you @nzakas!

**Review by lahmatiy — APPROVED** [review]
